repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        stages: [commit]
        language: system
        entry: uv run --python 3.13 ruff format --check
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        stages: [commit]
        language: system
        entry: uv run --python 3.13 ruff check
        types_or: [python, pyi]

      - id: basedpyright
        name: basedpyright
        stages: [commit]
        language: system
        entry: uv run --python 3.13 basedpyright
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: uv run --python 3.13 pytest -q
        pass_filenames: false
